rvm:
- 2.1.0
bundler_args: --without debug development
cache: bundler
script:
- bundle exec rake db:test:prepare
- bundle exec rake
before_script:
- cp .sample.env .env
- cp config/database.travis.yml config/database.yml
- psql -c 'create database hours_test' -U postgres
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
env:
  SECRET_KEY_BASE="$(bundle exec rake secret)"
